In [ ]:
a = 1

In [ ]:
isinstance(a, int)

In [1]:
a = "Hello Florida!"

In [2]:
isinstance(a, int)

False

In [3]:
a == "Hello Florida!"

True

In [4]:
print(a)

Hello Florida!


In [5]:
1,000,000

(1, 0, 0)

In [6]:
1_000_000

1000000

In [12]:
"{:,}".format(1_000_000)

'1,000,000'

In [13]:
print('C:\Python\transportation-tutorials')

C:\Python	ransportation-tutorials


In [14]:
print(r'C:\Python\transportation-tutorials')

C:\Python\transportation-tutorials


In [16]:
print("""\
Usage: florida-man [OPTIONS]
        -h            Display this usage message
        -t degrees    Set temperature in °F
        -a            Include alligators

""")

Usage: florida-man [OPTIONS]
        -h            Display this usage message
        -t degrees    Set temperature in °F
        -a            Include alligators




In [17]:
cities = ['Miami', 'Orlando', 'Tampa', 'Jacksonville']

In [20]:
cities[0:2]

['Miami', 'Orlando']

In [21]:
cities.append('Tallahassee')

In [22]:
cities

['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Tallahassee']

In [23]:
cities.append(123)

In [24]:
cities

['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Tallahassee', 123]

In [25]:
cities.pop()

123

In [26]:
cities

['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Tallahassee']

In [27]:
cities[2] = 'Tampa–St. Petersburg'
cities


['Miami', 'Orlando', 'Tampa–St. Petersburg', 'Jacksonville', 'Tallahassee']

In [28]:
counties = ('Miami-Dade', 'Orange', 'Hillsborough', 'Duval')

In [33]:
counties[0] = 'Miami'  # tuple is immutable 

TypeError: 'tuple' object does not support item assignment

In [34]:
jurisdictions = {'Miami': 'Dade County', 'Orlando': 'Orange County'}

In [35]:
jurisdictions['Jacksonville'] = 'Duval'

In [36]:
jurisdictions

{'Miami': 'Dade County', 'Orlando': 'Orange County', 'Jacksonville': 'Duval'}

In [37]:
print(jurisdictions['Miami'])

Dade County


In [39]:
print(jurisdictions['Orlando'])

Orange County


In [40]:
jurisdictions['Miami'] = 'Miami-Dade County'

In [41]:
jurisdictions

{'Miami': 'Miami-Dade County',
 'Orlando': 'Orange County',
 'Jacksonville': 'Duval'}

In [42]:
national_parks = {'Everglades', 'Biscayne', 'Dry Tortugas'}

In [43]:
national_parks

{'Biscayne', 'Dry Tortugas', 'Everglades'}

In [44]:
national_parks

{'Biscayne', 'Dry Tortugas', 'Everglades'}

In [46]:
x = 'Miami Beach'

if x in cities:
    print("found", x, "City")
elif x in counties:
    print("found", x, "County")
else:
    print("didn't find", x)

didn't find Miami Beach


In [47]:
for x in counties:
    print(x, 'County')

Miami-Dade County
Orange County
Hillsborough County
Duval County


In [49]:
x = 1
while x < 5:
    print(x)
    x += 1

1
2
3
4


In [50]:
x = 1
while x < 5:
    print(x)
    x += 1
    if x > 3:
        break

1
2
3


In [51]:
import os
import numpy as np
from transportation_tutorials import data as td

ModuleNotFoundError: No module named 'transportation_tutorials'

In [52]:

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
full : Return a new array of given shape filled with value.

Examples
--------
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=int)
array([0, 0, 0, 0, 0])

>>> np.zeros((2, 1))
array([[ 0.],
      

In [54]:
np?

Type:        module
String form: <module 'numpy' from '/Users/cheng_xi/.local/lib/python3.7/site-packages/numpy/__init__.py'>
File:        ~/.local/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x 

In [1]:

def greeting():
    print("Hello, Florida!")

In [2]:
greeting()

Hello, Florida!


In [3]:
def to_kilometers(miles, feet):
    distance = miles + feet/5280
    return 1.60934 * distance

to_kilometers(26, 1155)

42.194883125

In [4]:
def to_kilometers_b(miles, feet=0):
    distance = miles + feet/5280
    return 1.60934 * distance

to_kilometers_b(100)

160.934

In [5]:
1155/5280

0.21875

In [6]:
385/1760

0.21875

In [7]:
def to_kilometers_c(miles, feet=0, yards=0):
    distance = miles + feet/5280 + yards/1760
    return 1.60934 * distance

In [8]:
to_kilometers_c(26, yards = 385)

42.194883125

In [10]:
to_kilometers_c(26, feet = 1155)

42.194883125

In [11]:
to_kilometers_c(feet=1155, miles=26)

42.194883125

In [12]:
to_kilometers_c(feet=100, yards=0)

TypeError: to_kilometers_c() missing 1 required positional argument: 'miles'

In [18]:
# Functions that take an arbitrary number of arguments can do so using “star” notation
def county_names(*names):
    for name in names:
        print(name, "County")

In [19]:
county_names("Pinellas", "Leon", "Monroe")

Pinellas County
Leon County
Monroe County


In [20]:
def highway_names(*names, heading=None):
    if heading:
        print(heading)
    for name in names:
        print("-",name)

highway_names("Alligator Alley", "Magic Carpet", heading="Unofficial Names")

Unofficial Names
- Alligator Alley
- Magic Carpet


In [21]:
#Arbitrary keyword arguments can also be accepted using a double-star. 
#In this case, the double-starred argument is used within the function as a dictionary, 
#mapping the given keyword argument names to their values.

def more_highway_names(**names):
    for key, value in names.items():
        print(key,"is",value)

more_highway_names(I_75="Alligator Alley", US_1="Magic Carpet")

I_75 is Alligator Alley
US_1 is Magic Carpet


In [22]:
lambda km: km / 1.60934

<function __main__.<lambda>(km)>

In [23]:
list(map(lambda km: km / 1.60934, [5, 10, 42.194883125]))

[3.106863683249034, 6.213727366498068, 26.218749999999996]

In [2]:
import os
import numpy as np
import pandas as pd

In [27]:
pip install transportation_tutorials

     |████████████████████████████████| 36.5 MB 9.4 MB/s eta 0:00:01     |█████████▎                      | 10.6 MB 1.2 MB/s eta 0:00:23
     |████████████████████████████████| 93 kB 4.6 MB/s  eta 0:00:01
     |████████████████████████████████| 84 kB 5.1 MB/s  eta 0:00:01
     |████████████████████████████████| 928 kB 37.0 MB/s eta 0:00:01
     |████████████████████████████████| 13.0 MB 10.7 MB/s eta 0:00:01
     |████████████████████████████████| 13.9 MB 21.3 MB/s eta 0:00:01    |▉                               | 368 kB 21.3 MB/s eta 0:00:01
  Using cached cligj-0.5.0-py3-none-any.whl (5.7 kB)
ERROR: osmnx 0.14.1 has requirement matplotlib>=3.2, but you'll have matplotlib 3.1.3 which is incompatible.
ERROR: osmnx 0.14.1 has requirement numpy>=1.18, but you'll have numpy 1.16.0 which is incompatible.
ERROR: osmnx 0.14.1 has requirement requests>=2.23, but you'll have requests 2.22.0 which is incompatible.
Note: you may need to restart the kernel to use updated packages.


In [4]:
import transportation_tutorials as tt

ModuleNotFoundError: No module named 'contextily'

In [5]:
pip install contextily

     |████████████████████████████████| 17.4 MB 2.6 MB/s eta 0:00:01     |██████████████████████████▊     | 14.5 MB 2.6 MB/s eta 0:00:02
     |████████████████████████████████| 113 kB 49.5 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import transportation_tutorials as tt

In [2]:
from transportation_tutorials import data as td

In [2]:
import os
import numpy as np
import pandas as pd
import transportation_tutorials as tt

In [2]:
for i in 1 to 5:
    print(i)

SyntaxError: invalid syntax (<ipython-input-2-7864abb46b1a>, line 1)

In [5]:
for i in [1,2,3,4,5]:
    print(i)

1
2
3
4
5


In [6]:
for i in range(1,6):
    print(i)

1
2
3
4
5


In [8]:
speeds = {
    'rural highway': 70,
    'urban highway': 55,
    'residential': 30,
}

for i in speeds:
    print(speeds[i])

70
55
30


In [11]:
road_types = ['rural highway', 'urban highway', 'residential']

In [12]:
for i in road_types:
    print(speeds[i])

70
55
30


In [3]:
try:
    table = pd.read_csv('path/to/non-existant/file.csv')
except:
    table = pd.DataFrame() # set to blank dataframe
print(table)

Empty DataFrame
Columns: []
Index: []


In [4]:

try:
    table = pd.read_csv('path/to/non-existant/file.csv')
except FileNotFoundError:
    table = pd.DataFrame() # set to blank dataframe
print(table)

Empty DataFrame
Columns: []
Index: []


In [5]:
try:
    table = pd.read_csv(tt.data('THIS-FILE-IS-CORRUPT'))
except FileNotFoundError:
    table = pd.DataFrame() # set to blank dataframe
print(table)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 15: invalid start byte

In [6]:

try:
    table = pd.read_csv(tt.data('THIS-FILE-IS-CORRUPT'))
except FileNotFoundError:
    table = pd.DataFrame() # set to blank dataframe
except UnicodeDecodeError:
    table = pd.DataFrame(['corrupt!'], columns=['data'])
print(table)

       data
0  corrupt!


In [9]:
x = range(5000)
y = 0

for i in x:
    y = y + i**2
y

41654167500

In [10]:
x

range(0, 5000)

In [14]:
x=list(range(5000))

In [15]:
import numpy
z = numpy.arange(5000)
(z**2).sum()

41654167500

In [18]:
%%timeit
y = 0
for i in x:
    y = y + i**2

1.39 ms ± 28.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [19]:
%%timeit
(z**2).sum()

8 µs ± 50.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
a = numpy.asarray([11,22,33,44])
a

array([11, 22, 33, 44])

In [23]:
a.dtype

dtype('int64')

In [24]:
b = numpy.asarray([11,22,33,4.4])
b.dtype

dtype('float64')